// ********RoostGPT********
// Test generated by RoostGPT for test react-chat using AI Type Open AI and AI Model gpt-4-turbo-2024-04-09



// ********RoostGPT********
import React from 'react';
import { render } from '@testing-library/react';
import InfoBar from '../../../../../client/src/components/InfoBar/InfoBar.js';

describe('InfoBar Component', () => {
  test('should render the InfoBar component with the room name', () => {
    const { getByText } = render(<InfoBar room="testRoom" />);
    expect(getByText('testRoom')).toBeInTheDocument();
  });

  test('should display the online icon', () => {
    const { getByAltText } = render(<InfoBar room="testRoom" />);
    expect(getByAltText('online icon')).toBeInTheDocument();
  });

  test('should display the close icon', () => {
    const { getByAltText } = render(<InfoBar room="testRoom" />);
    expect(getByAltText('close icon')).toBeInTheDocument();
  });

  // Test link behavior (such as it goes to home "/" on click)
  test('should redirect to home on close icon click', () => {
    const { container } = render(<InfoBar room="testRoom" />);
    const link = container.querySelector('a');
    expect(link).toHaveAttribute('href', '/');
  });
});

